import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { Lobster_Two, Poppins, Rancho } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import theme from "./theme/themeConfig";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const lobsterTwo = Lobster_Two({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lobster-two",
  display: "swap",
});

const rancho = Rancho({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rancho",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${lobsterTwo.variable} ${rancho.variable}`}
    >
      <body>
        <ConfigProvider theme={theme}>
          <AntdRegistry>
            <Header />
            <main>{children}</main>
            <Footer />
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
